name: Build FastFetch 2.37.0 for OpenWrt 24.10.0

on:
  workflow_dispatch:

jobs:
  build-fastfetch:
    runs-on: ubuntu-latest

    steps:
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y wget build-essential zstd libssl-dev python3 rsync gettext libncurses-dev git cmake ninja-build

    - name: Download SDK dan Toolchain
      run: |
        wget https://downloads.openwrt.org/releases/24.10.0/targets/qualcommax/ipq807x/openwrt-sdk-24.10.0-qualcommax-ipq807x_gcc-13.3.0_musl.Linux-x86_64.tar.zst
        wget https://downloads.openwrt.org/releases/24.10.0/targets/qualcommax/ipq807x/openwrt-toolchain-24.10.0-qualcommax-ipq807x_gcc-13.3.0_musl.Linux-x86_64.tar.zst

    - name: Ekstrak SDK
      run: |
        mkdir -p sdk
        tar -I zstd -xvf openwrt-sdk-*.tar.zst -C sdk --strip-components=1
        tar -I zstd -xvf openwrt-toolchain-*.tar.zst -C sdk/staging_dir

    - name: Init SDK environment
      working-directory: ./sdk
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        rm -f .config
        echo "CONFIG_PACKAGE_fastfetch=y" > .config
        make defconfig

    - name: Create custom package
      working-directory: ./sdk
      run: |
        mkdir -p package/utils/fastfetch
        cat > package/utils/fastfetch/Makefile <<'EOL'
        include $(TOPDIR)/rules.mk

        PKG_NAME:=fastfetch
        PKG_VERSION:=2.37.0
        PKG_RELEASE:=1

        PKG_SOURCE:=fastfetch-$(PKG_VERSION).tar.gz
        PKG_SOURCE_URL:=https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/
        PKG_HASH:=a5739be74686fefc731f7ce1669c645ca98172ae3ed5e7c3d48176df43aea5af

        PKG_BUILD_DEPENDS:=meson/host
        PKG_INSTALL:=1
        PKG_BUILD_PARALLEL:=1

        include $(INCLUDE_DIR)/package.mk
        include $(INCLUDE_DIR)/cmake.mk

        define Package/fastfetch
          SECTION:=utils
          CATEGORY:=Utilities
          TITLE:=FastFetch
          DEPENDS:=+libpthread +librt +libncurses +libjson-c +libmagic +zlib +libopenssl
          URL:=https://github.com/fastfetch-cli/fastfetch
        endef

        define Package/fastfetch/description
        Modern system information tool for OpenWrt (Version $(PKG_VERSION))
        endef

        CMAKE_OPTIONS += \
          -DBUILD_TESTS=OFF \
          -DENABLE_LIBPCI=OFF \
          -DENABLE_VULKAN=OFF \
          -DENABLE_WAYLAND=OFF \
          -DENABLE_X11=OFF \
          -DCMAKE_BUILD_TYPE=Release

        define Package/fastfetch/install
          $(INSTALL_DIR) $(1)/usr/bin
          $(INSTALL_BIN) $(PKG_BUILD_DIR)/fastfetch $(1)/usr/bin/
          $(INSTALL_DIR) $(1)/usr/share/fastfetch/presets
          $(CP) $(PKG_BUILD_DIR)/presets/* $(1)/usr/share/fastfetch/presets/
        endef

        $(eval $(call BuildPackage,fastfetch))
        EOL
        
        # Perbaiki indentasi dengan tab
        sed -i 's/^  /\t/g' package/utils/fastfetch/Makefile

    - name: Pre-download source
      working-directory: ./sdk
      run: |
        mkdir -p dl
        wget https://github.com/fastfetch-cli/fastfetch/archive/refs/tags/2.37.0.tar.gz -O dl/fastfetch-2.37.0.tar.gz

    - name: Verify hash
      working-directory: ./sdk
      run: |
        echo "Hash yang valid untuk FastFetch 2.37.0:"
        curl -sL https://api.github.com/repos/fastfetch-cli/fastfetch/releases/tags/2.37.0 | grep browser_download_url | grep tar.gz | cut -d '"' -f 4 | xargs curl -sL | sha256sum
        echo "Hash file yang didownload:"
        sha256sum dl/fastfetch-2.37.0.tar.gz

    - name: Build package
      working-directory: ./sdk
      run: |
        make package/utils/fastfetch/compile -j1

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: fastfetch-ipk
        path: sdk/bin/packages/*/base/fastfetch*.ipk
